# -*- coding: utf-8 -*-

{
    'name': 'Manufacturing Dental',
    'version': '12.0.1.0.0',
    'summary': 'All customization for dental project',
    'category': 'General',
    'author': "",
    'company': '',
    'website': "",
    'depends': ['base','sale','sales_team','mail','account','stock','sale_management',],
    'data': ['data/sequence.xml',
             'data/mail_template.xml',
             'data/hr_payroll_data.xml',
             'report/manufacturing_report_view.xml',
             'report/manufacturing_template_report.xml',
             'security/sale_menu.xml',
             'security/user_groups.xml',
             'security/ir.model.access.csv',
             'views/section.xml',
             'views/dental.xml',
             'views/sale_order.xml',
             'views/hide_menu_sale.xml',
             'views/invoice_report.xml',
             'views/contacts_view.xml',
             'views/product_template.xml',
             'views/hr_contract_views.xml'],
    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
